### ISSUE TITLE
Nested awareness

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#128]
**Describe the current state of the problem**
Currently, ct.js assumes a more traditional way of writing games: that you run one room at a time that consists of a flat list of entities (tiles, copies, backgrounds). This produces a set of limitations: 

* really big worlds with tons of entities will lag, as everything is computed at once;
* **(solved)** no separate layers that would allow transforming one set and not another. Say you have an RTS where you can zoom in and out (and even rotate) but UI should stay the same;
* nested copies don't work with world positions, which break collisions with the outer world;
* **(partially solved)** there is no easy way to use prefab rooms (for modular level building and procedural generation), because of the lack of UI tools in ct.js and collisions.
    * prefab rooms are also a shortcut to UI editor #53 

**Describe the solution you'd like**

* [x] Merge #127 that would allow a proper cleanup of nested structures
* [x] Rewrite room editor with pixi.js #39 as it is a foundation for most further UI tools
* [ ] Change `ct.place` so it works with world coordinates
* [x] Add an ability to put one room into another;
    * [ ] It would be cool if game devs could control when these rooms are loaded (e.g. based on camera position, or by triggers #67 ) and unloaded (aka a streaming system).
        * Isn't it a game developer's task, though?
* [x] Add API to work with **UI coordinates**:
    * [x] `ct.mouse.xui`, `ct.mouse.yui`;
    * [x] :arrow_up: the same for ct.touch
* [x] Add API to easily position layers
    * It can be made with parameters for prefabs that would tell whether a layer should use screen UI or world ones, should it follow the camera or not.

At the same time, ct.js must stay enjoyable and available for the good ol' traditional game dev approach.

---
**UI coordinates**: most known in other engines as screen coordinates, though they do differ as `ct.viewWidth` is not always the size of the canvas in _screen pixels_. These will be in a range from 0 to ct.viewWidth (ct.viewHeight) and be used in UI layers.

**Comment by leedigital** [comment]
This is a feature that I would like to work on.... ^_^

**Comment by CosmoMyzrailGorynych** [comment]
@leedigital Cool! What exactly do you want to work on?
I have some work on a new room editor, but it is way, waaay far away from finishing.

**Comment by leedigital** [comment]
whatever you want me to do first ... but I think putting one room in another is something I really want to do.... ^_^

**Comment by CosmoMyzrailGorynych** [comment]
Then your starting point is an internal method `ct.rooms.forceSwitch` :muscle: https://github.com/ct-js/ct-js/blob/develop/app/data/ct.release/rooms.js#L103
Don't forget about a companion pull at https://github.com/ct-js/docs.ctjs.rocks

**Comment by CosmoMyzrailGorynych** [comment]
So a fat chunk of improvements in this direction was made in https://github.com/ct-js/ct-js/commit/902c92d1376427094afaecbb7736ceacf3eaae22 with the help of @leedigital. It introduces nesting rooms, `ct.camera`, and the concept of UI coordinates opposed to game coordinates. And it all meets together nicely.

There are WIP docs at https://github.com/ct-js/docs.ctjs.rocks/tree/v1.3
