### ISSUE TITLE
Integration into system and installers

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#200]
**Is your feature request related to a problem?**
ct.js is a pretty self-contained app, but without additional efforts, setting it up may be cumbersome or problematic for most users. This issue includes talks on installers, integration with systems, and shell usage.

Pros:

* Much better onboarding, which is especially important for educational institutions.
* Less fuzz for users to update ct.js (in case itch.io app is not installed).
* A couple clicks to integrate into menus and bind extensions.

**Describe the solution you'd like**

*Distribution and installation:*

- [x] Create an installer for Windows (e.g. an NSIS one) #349 
- [ ] Write an install procedure for Mac (needs research)
- [ ] Create an AppImage for Linux
- [ ] Create a flatpak
  - [ ] Publish in Flathub
- [ ] Bake packages for popular Linux system package managers (aur, rpm, deb)

- [ ] Integrate everything into build pipeline (Travis CI)

*General usage:*

- [ ] Open a project by double-clicking a `.ict` file. Note that ct.js is single-instance only.
- [ ] Add options into ct.js settings to bind itself with its extensions

**Optional solutions**

- Chocolatey for Windows
- Steam?!?!?!?!

**Additional context**

Feel free to discuss the topic and create detailed issues about solving separate tasks.

**Comment by CosmoMyzrailGorynych** [comment]
cc @naturecodevoid

**Comment by amsam0** [comment]
My initial idea:

Python installer using [PyQt5](https://www.riverbankcomputing.com/static/Docs/PyQt5/index.html):
  - Windows style (but cross-platform)
  - Bundled using [PyInstaller](https://pyinstaller.readthedocs.io/)
    - This should allow for users that don't have python to run the installer
  - It can also save the installation location to allow for updates
  - It grabs ct.js through https://ctjs.rocks/download/ or https://github.com/ct-js/ct-js/releases/latest
    - Getting the latest version may be a little complicated
  - Install process:
    - Unzip the release
    - Copy it to the specified location

This way we don't have to make separate versions for each operating system.
Also, if you're wondering why python/qt, its mainly for performance.

I do think that the solutions you mentioned would be better, though.

Let me know what you think.

**Comment by CosmoMyzrailGorynych** [comment]
The latest releases at Github are always at https://github.com/ct-js/ct-js/releases/latest

The latest version number is received from itch, at `https://itch.io/api/1/x/wharf/latest?target=comigo/ct&channel_name=${channel}`
Usage example is at https://github.com/ct-js/ct-js/blob/develop/src/riotTags/project-selector.tag#L182

https://ctjs.rocks/download/ currently points to github releases (:

> Windows style (but cross-platform)

Sounds great!

**Comment by amsam0** [comment]
I've made a branch for the python installer [here](https://github.com/naturecodevoid/ct-js/tree/issue-200-installer-python).

I'll probably make a pr tomorrow when it's mostly ready.

Edit: https://github.com/ct-js/ct-js-site/blob/master/src/_data/downloads.js seems like another good example

**Comment by StuckUpCreations** [comment]
my "change exports location" thread is related to this one.. when that is fixed i can create an AppImage too, but AppImage now will have same problem so i will wait.
