### ISSUE TITLE
Stuff to do for v3

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#343]
- [x] #215 
  - [x] Add events to the Matter.js lib
  - [x] Review catmods list to see which can benefit from having custom events
    - [ ] ct.desktop
    - [ ] ct.nakama?
    - [ ] ct.yarn!
  - [x] Update demos and examples
  - [x] Update tutorials ;-; All hail @firecakes!
- [x] ~~#346~~ Postponed till v4 release
- [x] #39 and #76 
- [x] Apparently, particle library got lost during the making of the asset gallery
- [ ] ~~#355~~ New nw-builder is a buggy disfunctional mess.
  - [x] ~~#349~~ Made a web installer instead
- [x] A small web installer for Windows would be good.
- [x] Doc updates
  - [x] Update screenshots and instructions in tutorials for the new room editor
  - [x] Update docs for room editor
  - [ ] Dragging Copies Around can be updated for the events system
- [x] Migration guide
  - [x] Custom properties of copies inside the room editor are currently lost; can be fixed through a migration script, though
  - [x] For some reason, placholder images in LabRaid demo had invalid names, breaking project loading. Other projects might be susceptible to this disease.
