### ISSUE TITLE
Stuff to do for v4

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#383]
- [x] https://github.com/ct-js/ct-js/issues/346
- [x] https://github.com/ct-js/ct-js/issues/318
  - [x] Two files (pixi typings and ct.js ones) can be stitched into one. This should be a decent workaround for the blocking issue.
  - [x] Emitter tandem editor is currently a broken mess. Otherwise, moving to pixi v7 is done.
  - [x] pixi.js seems to be dragged into ct.js file anyways. Running in an external browser 
doesn't work.
    - Fixed already? Or dependent on specific branch?
  - [x] Getting tons of lost sourcemap warnings in ~~both the exported games~~ (no warnings on pixi-v7) and ct.IDE.
    - One of the problems was that pixi-sound branch used the sound package dynamically 
    - ~~Nw.js bug?~~ No, fixed in 0.62.1.
    - Or is it? v0.82.0 does not have sourcemap warnings, BUT can't open ct.js projects due to problems in Pixi.js' Loader. https://github.com/pixijs/pixijs/issues/9568 Must be related, nw.js uses `chrome-extension://` in paths, as well as `file:///` with the triple slash.
    - sourcemaps in nw.js v0.75.1 doesn't work. So doesn't 0.78.1.
    - Sourcemaps fix in 0.79.0 (an obviously new version of chrome debugger appears), but so does pixi.js break.
    - I just wish someday a day comes when upstream stuff just works.
- [x] The interconnected trio:
  - https://github.com/ct-js/ct-js/issues/306
  - https://github.com/ct-js/ct-js/issues/75
  - https://github.com/ct-js/ct-js/issues/48
- [x] #445 (discussed in #203, too)
- [x] https://github.com/ct-js/ct-js/issues/424
- [ ] ~~Complete skeletons support in the client lib and room editor (can be a part of #448)~~ Spine Runtime is not OSS, can't do that
- [ ] ~~https://github.com/ct-js/ct-js/pull/436~~
- [x] cherry-pick https://github.com/ct-js/ct-js/pull/444 into `pixi-v7`
- [x] Migration guide & Doc updates (https://github.com/ct-js/docs.ctjs.rocks/issues/111)
- [x] New APIs need to be documented:
  - [x] `behaviors` as part of #445 
  - [x] `sounds` as part of #346
  - [x] `settings`
- [x] Make sure everything in [the Overlook board](https://github.com/orgs/ct-js/projects/5/views/7) in columns Max Attention, Current Release, In progress is done as well, as there are cards not converted to issues yet.

Optional:

- [x] https://github.com/ct-js/ct-js/issues/423
- [x] #448 
- [ ] https://github.com/ct-js/ct-js/issues/331 — Not that needed as we have CoffeeScript now

**Comment by CosmoMyzrailGorynych** [comment]
no
