### ISSUE TITLE
Rewrite room editor with pixi.js

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#39]
This will reduce further development complexity, and make drawing faster and closer to the final game. The current canvas-based editor quickly loses its maintainability.

Also, see #40, #76, and #57 

A mockup: https://www.figma.com/file/5ranH0vsypOnCYGIKntGVF/Ct.js-v2?node-id=1%3A2

## TODO

* [x] Feature parity with the old editor
  * [x] Camera controls
  * [x] Rectangular grid
  * [x] Drawing regular copies
  * [x] Drawing tiles (pivots are wrong rn)
  * [x] Drawing backgrounds
  * [x] Placing copies
  * [x] Placing tiles
  * [x] Managing backgrounds
  * [x] Custom properties for copies, added by a user without modules
  * [x] Viewport management updates
  * [x] Background color updates
  * [x] Free placement mode for tiles and copies (alt key)
  * [x] Better removal mode feedback (ctrl key)
  * [x] actually save changes 🤣 
* [x] Simulation controls
* [x] Transformer
* [x] Group transformation
* [x] Ability to ignore certain entity groups during selection (how do I fit it into UI? 🤔)
* [x] Ctrl+C, Ctrl+V
* [x] Ctrl+Z, Ctrl+Shift+Z (#76)
* [x] Delete key for the current selection
* [x] Make sure that tint and transforms are applied to both copies and tiles in the exported games
* [x] ~~Apparently it is time to introduce more complex collision checks for tiles 🤔 as they can now be transformed and rotated.~~ Oh well. They had already supported them.

New functionality:

* [x] Isometric/diagonal grids
* [ ] Particle tandems
* [ ] Ambient sounds
* [ ] Triggers (#67)
* [ ] Waypoints/paths
* [ ] Additional view options:
  * [ ] Custom properties display
  * [x] X-Ray mode
  * [ ] Collision group display? Collision shapes?

**Comment by CosmoMyzrailGorynych** [comment]
So, *the Vision*:

- The editor partially simulates the scene, by playing sprite animations, performing background movement. Toggleable/configurable.
- Everything is in WebGL (in PIXI), and should resemble the results seen in ct.js game as close as possible.
- With the addition of hand-placed sounds and particle systems (SOON), the editor will allow for a more immersive workflow, that will greatly contribute to the level design pipeline (more interactive WYSIWYG in editor > less testing in a debugger. It is also *just cool*).
- Copies and tiles should be transformed as layers in Photoshop or other graphics editing package — with multiple selections, rotation and scale handles, ctrl+C, ctrl+V; bring artistic value and composition to the workflow.
- Undo/redo must also be present, as it is easy to mess the things up when moving lots of things around, especially when using no grid (#76).
- Do provide tools for extended scripting with custom copies' parameters (#40) and triggers. This will also pave an avenue for level designers that don't code.

**Comment by CosmoMyzrailGorynych** [comment]
# Outdated sketches

![](https://cdn.discordapp.com/attachments/490056845025869858/618570247191920651/IMG_20190904_101022_6-01.jpeg)
![](https://cdn.discordapp.com/attachments/490056845025869858/618570502214254623/JPEG_20190904_101754.jpg)
![](https://cdn.discordapp.com/attachments/490056845025869858/618570694589939722/JPEG_20190904_101845.jpg)

**Comment by CosmoMyzrailGorynych** [comment]
https://github.com/jedateach/pixijs-free-transform-tool

**Comment by CosmoMyzrailGorynych** [comment]
Initial release-ready set of functionality is ready. Further additions will when their dependencies are complete. The first one will be with sounds, probably.
