### ISSUE TITLE
Behaviors framework

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#445]
Short description: Behaviors are a new asset type designed to solve problems with modular gameplay elements and repeating/shared code. Each template/room can have an arbitrary behaviors that augment their events.

Additional context: #203 and its discussion

# TODO

- [x] Implement the basic behaviors functionality for ct.IDE, exporter, and the client lib
- [x] Provide API to add and remove behaviors dynamically
  - Is it actually possible? It is perfectly doable with code domains `thisOnStep`, `thisOnCreate`, `thisOnDraw`, and `thisOnDestroy`, but it is definitely not applicable to `rootRoomOnCreate`, `rootRoomOnStep, `rootRoomOnDraw`, and `rootRoomOnLeave`, as their code relies on static code templating to get the target copies by their template name from within the main room. This will require more complex means for tracking copies that need root room events.
  - I'll do the dumb and wet (as opposed to DRY) approach; the gzip will handle all it anyways. Maybe form behaviors' code into functions so it is not _that_ wet.
  - On the other side, few catmods actually use root room functionality (Matter.js, network-related catmods). Perhaps we expose limited functionality and signal about specific event incompatibilities in the "Add event" menu.
- [x] Add UI indicators on whether specific events can make behaviors static
- [x] Add asset icons for static behaviors
- [x] Write docs on this API

# Bonus points

- [ ] Behaviors that require behaviors, with the requirements added to templates automatically with sorting
- [x] Custom fields designed in behaviors and output in template/room editors
- [x] Easy sharing and import of behaviors

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/be78c30f3c1722153f54892fb32137a75fdeec68 :tada:
