### ISSUE TITLE
Stuff to do for v5

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#482]
- [ ] ~~Hopefully ct-js/ct-js-old#450~~
  - too many bugs in newer versions of nw.js
- [ ] ~~#515~~
  - Little benefit till ct-js/ct-js-old#450 is done, plus facing bizarre inconsistencies that are not in migration guides
- [ ] ~~Make ct.js projects at export time rollup-able ESM+NPM projects~~ postponed till better days
  - Support for ESM modules
  - Less shenanigans in the client lib with pixi.js and other dependencies
- [ ] ~~#431~~
  - Unfortunately too buggy atm
- [x] Revisit ct-js/ct-js-old#331
- [x] ct-js/ct-js-old#516
  - One asset as a font family, multiple styles
  - IAsset will finally have a `name` property, which will simplify codebase
