### ISSUE TITLE
Organize assets with folders

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#75]
# Meta

This issue covers:

* a new asset browser that supports folders with projects' hierarchical file-based structure
* multi-tabbed view (one asset = one tab; multiple assets of one type can be opened) (#48)
* changes in internal APIs that make the above stuff possible
* re-write of asset pickers. Will reuse the asset browser component.

# Links

* ~~The spec and working draft of internal working of the  file-based structure:
   https://docs.google.com/document/d/1qc1VOMZw4ddV2O4VCzbMncZP1HajTU1oK6Rjwz4Tlog/edit?usp=sharing~~ outdated as heck
* Mockups of the interface: 
  https://www.figma.com/file/5ranH0vsypOnCYGIKntGVF/Ct.js-v2?node-id=0%3A1
* WIP branch: 
  ~~https://github.com/ct-js/ct-js/tree/issue-75-asset_folders~~
  https://github.com/ct-js/ct-js/tree/unified-assets
* Discuss on Discord:
   https://discord.gg/kHWwDvQjrb

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Apr 1, 2019, 02:46

Gravit designer has a really neat file manager

![image](/uploads/443b28355205278d7257fce98dbb1bb1/image.png)

**Comment by CosmoMyzrailGorynych** [comment]
As seen in Gravit Designer, which had a somewhat similar asset view before.

![изображение](https://user-images.githubusercontent.com/3174357/63301789-8b551900-c32f-11e9-917a-787f8a781bcc.png)

**Comment by CosmoMyzrailGorynych** [comment]
![image](https://user-images.githubusercontent.com/3174357/67155393-7bbf7400-f362-11e9-9366-e22b11c11b88.png)
![image](https://user-images.githubusercontent.com/3174357/67155394-867a0900-f362-11e9-893f-9cd8d871c3ac.png)

**Comment by amsam0** [comment]
Could I try to separate the .ict file into folders/files?

**Comment by CosmoMyzrailGorynych** [comment]
Let's discuss it first here: https://docs.google.com/document/d/1qc1VOMZw4ddV2O4VCzbMncZP1HajTU1oK6Rjwz4Tlog/edit?usp=sharing

**Comment by amsam0** [comment]
I don't have permission? We could do it on Discord

**Comment by CosmoMyzrailGorynych** [comment]
Could you try again? I've fixed the privacy settings

**Comment by rBok6** [comment]
The folder grouping is pretty much what I had in mind but the other idea of showing categories in room editor #189 wasn't taken into consideration so I made this to explain myself better. This approch could be useful in both Textures and Types tab and categories created by the user should appear in the room editors as seen in this image that i made for you.

![ctjsissue](https://user-images.githubusercontent.com/13161094/81590186-6e161e00-9388-11ea-9032-b2c593d59468.png)

**Comment by CosmoMyzrailGorynych** [comment]
@rBok6 The aim of this issue is to organize _everything_ with folders, without separation between textures, types, rooms, and other assets. It will be more like an asset organization seen in Unity / Unreal Engine because it is more scalable (and more logical) for bigger games, and it will cover more than just a type picker in the room editor. Sooooo it does cover your original issue. Sorry for heartlessly closing it without further explanation. 😅 

Regarding the type picker, I've mocked up this panel before:

![image](https://user-images.githubusercontent.com/3174357/81937315-97180680-9647-11ea-836e-fdd4e1062338.png)

This is very raw but hopefully explains the idea.

**Comment by rBok6** [comment]
Cool, that looks neat. I didn't know you were redesigning the whole thing. 😍 That looks so much better.

**Comment by CosmoMyzrailGorynych** [comment]
# TODO

**General:**

* [x] Asset registry thingy
* [x] Asset browser
    * [x] Minimal functionality :construction:
    * [ ] Multi-selection and bulk operations
    * [ ] Filtering :construction:
    * [ ] Search
* [ ] Tabbed interface :construction:
* [ ] Cross-reference opening API
* [ ] Editing cross-notifications for updating tabs' state when dependent assets were updated
* [ ] Saving project :construction:
* [ ] Loading project :construction:
* [ ] Older projects' conversion

**Typings for assets' meta files (`name.ct${assetType}`): :construction:**

* [x] Generic asset
* [x] Project
* [x] type
* [x] room
* [x] sound
* [x] style
* [x] font
* [x] skeleton
* [x] texture
* [x] tandem

**CRUD operations:**

* [x] Universal methods :construction:
* [ ] type
* [ ] room
* [ ] sound
* [ ] style
* [ ] font
* [ ] skeleton
* [ ] texture
* [ ] tandem

**Leftovers:**

* [ ] Type picker in the room editor
* [ ] Texture picker in the room editor (for backgrounds, for tiles)
* [ ] Texture picker in the type editor
* [ ] Texture picker in the tandem editor
* [ ] Font picker in the style editor

And...

* [ ] **The exporter \@_@**

**Comment by CosmoMyzrailGorynych** [comment]
TODO

- [ ] Add a "New asset" menu
- [ ] Make sure folder creation and editing works
- [ ] Check breadcrumbs functionality
- [ ] Add folder navigation
- [ ] Drag'n'drop assets into folders
- [ ] Drag'n'drop files to import them as assets
- [ ] Multiple asset selection
  - [ ] Through ctrl/shift keys
  - [ ] Through box select
- [ ] Show metadata with icons

**Comment by CosmoMyzrailGorynych** [comment]
Closed in https://github.com/ct-js/ct-js/commit/1920e766f1fecca64d67ace8b008384102d86ce8
