### ISSUE TITLE
Undo/redo in Rooms

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#76]

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Mar 16, 2019, 16:05

Maybe do it with an Array subclass, that logs all pushes/splices intenally?

**Comment by CosmoMyzrailGorynych** [comment]
In GitLab by @CoMiGo on Mar 16, 2019, 16:07

Already exists at https://www.npmjs.com/package/historyarray  
Seems pretty easy to implement, then :eyes:

**Comment by CosmoMyzrailGorynych** [comment]
Related: #39. Should actually be a built-in feature of it, not an enhancement added lately, or it will be too hard to implement it as the editor does not comply to MVC model, thus we can't just record the history of changes to a plain JS room object.

**Comment by amsam0** [comment]
~~While #39 isnt finished, I could make an attempt at this once I finish the zooming pr (#180)~~ ~~I'd like to try and do this.~~

**Comment by CosmoMyzrailGorynych** [comment]
Working on as part of #39

**Comment by CosmoMyzrailGorynych** [comment]
# TODO

- [x] Create copies
- [x] Create tiles
- [x] Delete copies (eraser mode in copies tool)
- [x] Delete tiles (eraser mode in tiles tool)
- [x] Delete with select tool
- [x] Pasting stuff
- [x] Transform with select tool
- [x] Transformation changes made with select tool's side panel
- [x] Add tile layer
- [x] Remove tile layer
- [x] Tile layer depth change
- [x] Background color change, viewport prop. change (can be unified into one operation)
- [x] Background prop. change (can be unified with the previous one as well)
  - [x] ~~Will probably need to handle texture change separately~~ naaah
- [x] Add background
- [x] Remove background

Did I miss anything? Eh, probably not that important.

![Image](https://user-images.githubusercontent.com/3174357/185396973-aa452b2f-e9a3-4fba-8528-65e4d3cc8b0a.png)
